[package]
name = "mayball-info"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
icalendar = "0.16.12"
rocket = "0.5"
rocket_dyn_templates = {  version="0.2.0", features=["handlebars"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.39"
